														-- TAO RA 1 DATABASE CO TEN TRUONGHOC1 

CREATE DATABASE IF NOT EXISTS TRUONGHOC1;
USE TRUONGHOC1 ;
														-- TỒN TẠI TABLE THÌ TIẾN HÀNH XÓA TABLE
DROP TABLE IF EXISTS HOC;
DROP TABLE IF EXISTS TRUONG;
DROP TABLE IF EXISTS HS ;

CREATE TABLE TRUONG (
    MATR VARCHAR(20) PRIMARY KEY,
    TENTR VARCHAR(100) NOT NULL,
    DCHITR VARCHAR(100) NOT NULL
);

CREATE TABLE HS (
    MAHS VARCHAR(20) PRIMARY KEY ,
    HO VARCHAR(20) NOT NULL,
    TEN VARCHAR(20) NOT NULL,
    CCCD VARCHAR(20) ,
    NTNS DATE NOT NULL,
    DCHI_HS VARCHAR(100) NOT NULL,
    CONSTRAINT UQ_HS_CCCD UNIQUE(CCCD) 				    -- TẠO 1 RÀNG BUỘC LÀ DUY NHẤT CHO TRƯỜNG CCCD
);

CREATE TABLE HOC (
    MATR VARCHAR(100),
    MAHS VARCHAR(20),
    NAMHOC VARCHAR(20),
    DIEMTB FLOAT,
    XEPLOAI VARCHAR(20),
    KQUA VARCHAR(20),
    PRIMARY KEY (MATR, MAHS, NAMHOC),					-- TẠO CÁC KHÓA CHÍNH CHO BẢNG 
    FOREIGN KEY (MATR) REFERENCES TRUONG(MATR),			-- THAM CHIẾU CÁC KHÓA TỚI TỪNG BẢNG 
    FOREIGN KEY (MAHS) REFERENCES HS(MAHS)				-- THAM CHIẾU CÁC KHÓA TỚI TỪNG BẢNG 
);

